grid:
  unique_network_name: "162_sph_272rot"
  rotation_algorithm: "hypercube"
  rotation_random_seed: 1
  N_rotations: 272
  periodic_in: [ False, False ]
  translation_algorithm: "spherical"
  translation_subgrids_A: [ 162, [1.5, 10, 10] ]

pseudotrajectory:
  molecule_1: "benzene"
  molecule_2: "fluorobenzene"
  structure_ending: "gro"
  trajectory_ending: "xtc"

analysis:
  energy_program: "GROMACS"
  view_index: [ 1 ]
  length_shortened_trajectory_ns: 10
  energy_types: ["LJ (SR)", "Coulomb (SR)"]
  upper_E_limit: 0
  analyse_first_N_frames: None

sqra:
  sigma: 0
  tolerance_eigendecomposition: 0

eigenvectors:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 12
  num_extremes_to_plot: 10