grid:
  unique_network_name: "200_structures"
  rotation_algorithm: "hypercube"
  rotation_random_seed: 1
  N_rotations: 200
  translation_algorithm: "cartesian"
  periodic_in: [False, False, False]
  translation_subgrids_A: [ [0, 0.1, 1], [ 0, 0.1, 1], [10.0, 10.0, 1] ]

pseudotrajectory:
  molecule_1: "benzene2"
  molecule_2: "benzene2"
  structure_ending: "xyz"
  trajectory_ending: "xyz"

analysis:
  energy_program: ORCA
  length_shortened_trajectory_ns: 10
  energy_types: ["LJ (SR)", "Coulomb (SR)"]
  upper_E_limit: 0
  analyse_first_N_frames: None
  parts_to_perform: ["make_pseudotrajectory"]

curta:
  num_batches: 40
  num_structures_per_batch: 400

sqra:
  capping_factor: 2000
  cutting_factor: 1e300
  tolerance_rate_matrix_row_sum: 1e-6

eigenvectors:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 4
  num_extremes_to_plot: "auto"