pseudotrajectory:
  structure_ending: "gro"
  trajectory_ending: "xtc"
  input_structure_ending: "gro"
  cuboid_cell: [14.5086, 12.564816173346905, 11.84622229]

analysis:
  every_ith_energy: 1
  energy_program: GROMACS
  zoom_level: 0
  view_index: [ 1 ]
  length_shortened_trajectory_ns: 10
  analyse_first_N_frames: None
  plot_m1_as: "Licorice"
  plot_m2_as: "Licorice"
  parts_to_perform: ["make_grid", "make_pseudotrajectory", "plot_some_frames", "get_energy_pseudosimulation",
                     "plot_lowest_energies", "get_energy_simulation", "assign_trajectory", "sqra",
                     "prepare_all_on_curta", "msm", "all_translations_all_rotations", "make_pseudotrajectory_lammps"]

msm:
  sigma: 1.0
  tolerance: 0
  taus: [1, 2, 3, 5, 10, 20, 30, 50, 100, 200, 300, 500, 1000]

sqra:
  # rate matrix reduction
  capping_factor: None
  cutting_factor: "auto"
  tolerance_rate_matrix_row_sum: 1e-12
  # eigendecomposition
  tolerance_eigendecomposition: 0
  sigma: 0
  flow_to_bulk: 675 # per ns
  concentration_in_bulk: 0.033422 #molecules/A^3
  energy_kJ_mol_bulk: -2.808216
  allow_diffusion_to_bulk: False
  diffusion_coefficient: 230 # A^2/ns

curta:
  num_batches: 0
  num_structures_per_batch: 0

eigenvectors:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 4
  num_interesting_eigenvectors_as_lines: 5
  num_extremes_to_plot: "auto"