grid:
  N_rotations: 272
  translation_subgrids_A: [ [-10, 10, 10], [-10, 10, 10], [-10, 10, 20] ]

pseudotrajectory:
  molecule_1: "benzene"
  molecule_2: "benzene"

analysis:
  energy_program: "GROMACS"
  parts_to_perform: ["make_grid", "make_pseudotrajectory",
                     "get_energy_pseudosimulation",
                     "sqra", "plot_lowest_energies"]

sqra:
  cutting_factor: 1e10
  diffusion_coefficient: 54.9 # A^2/ns

eigenvectors:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 12
  num_extremes_to_plot: 5



