grid:
#  unique_network_name: "60_60_60"
#  rotation_algorithm: "hypercube"
#  rotation_random_seed: 1
#  N_rotations: 1
#  translation_algorithm: "cartesian"
#  periodic_in: [False, False, False]
#  translation_subgrids_A: [ [-20, 20, 60], [-20, 20, 60], [-20, 20, 60] ]
  unique_network_name: "periodic_cartesian_1"
  rotation_algorithm: "hypercube"
  rotation_random_seed: 1
  N_rotations: 1
  translation_algorithm: "cartesian"
  periodic_in: [True, True, True]
  translation_subgrids_A: [ [0, 14.5086, 10], [0,  12.564816173346905, 10], [0, 11.84622229, 10] ]

pseudotrajectory:
  molecule_1: "MOF_num"
  molecule_2: "AR"
  structure_ending: "gro"
  trajectory_ending: "xtc"
  input_structure_ending: "xyz"
  cuboid_cell: [29.0172, 25.12963234669381, 23.69244458]

msm:
    taus: [1, 2, 3, 5, 10, 20, 30, 50, 100, 200]

analysis:
  energy_program: "LAMMPS"
  every_ith_energy: 1
  view_index: [ 4 ]
  length_shortened_trajectory_ns: 10
  energy_types: ["LJ (SR)", "Coulomb (SR)"]
  upper_E_limit: 0
  analyse_first_N_frames: None
  plot_m1_as: "Licorice"
  plot_m2_as: "VDW"
  parts_to_perform: ["make_pseudotrajectory", "make_pseudotrajectory_lammps", "msm", "assign_trajectory"] # "msm",

curta:
  num_batches: 40
  num_structures_per_batch: 400

sqra:
  #capping_factor: 3000
  #cutting_factor: 1e6
  tolerance_rate_matrix_row_sum: 1e-8
  sigma: 0
  tolerance_eigendecomposition: 0

eigenvectors:
  num_interesting_timescales: 4
  num_interesting_eigenvectors: 8
  num_extremes_to_plot: 20
  num_interesting_eigenvectors_as_lines: 4