PATH_OUTPUT_ROTGRIDS = 'output/grid_files/'
PATH_OUTPUT_PT = 'output/pt_files/'
PATH_INPUT_BASEGRO = 'input/base_gro_files/'
PATH_OUTPUT_GRIDPLOT = 'output/figures_grids/'
PATH_OUTPUT_GRID_ANI = 'output/animations_grids/'
PATH_OUTPUT_GRIDORDER_ANI = 'output/animations_grid_ordering/'
