PATH_OUTPUT_ENERGIES = 'output/data/energies/'
PATH_OUTPUT_PT = 'output/data/pt_files/'
PATH_INPUT_BASEGRO = 'input/'
PATH_OUTPUT_PLOTS = 'output/figures/'
PATH_OUTPUT_ANIS = 'output/animations/'
PATH_OUTPUT_LOGGING = 'output/data/logging/'
PATH_OUTPUT_AUTOSAVE = 'output/data/autosave/'
